apiVersion: v1
kind: Service
metadata:
  name: argo-workflows-server-nodeport
  namespace: argo-workflows
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argo-workflows-server
  ports:
    - name: http
      port: 2746
      targetPort: 2746
      nodePort: 30746
